### ISSUE TITLE
Fails to install on Heroku: VIRTUAL_ENV variable is not found

### ISSUE THREAD

**Issue by keiw** [roadsideseb/virtual-node#3]
Here is the stacktrace i get trying to install virtual-node on Heroku (python 2.7.3 rutime) using default toolblet:

``` python
 Downloading/unpacking virtual-node==0.0.1 (from -r requirements.txt (line 23))
         Downloading virtual-node-0.0.1.tar.gz
         Running setup.py egg_info for package virtual-node
           Traceback (most recent call last):
             File "<string>", line 14, in <module>
             File "/app/build/virtual-node/setup.py", line 15, in <module>
               class node_install(install):
             File "/app/build/virtual-node/setup.py", line 16, in node_install
               env_dir = os.environ['VIRTUAL_ENV']
             File "/app/.heroku/python/lib/python2.7/UserDict.py", line 23, in __getitem__
               raise KeyError(key)
           KeyError: 'VIRTUAL_ENV'
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):

         File "<string>", line 14, in <module>

         File "/app/build/virtual-node/setup.py", line 15, in <module>

           class node_install(install):

         File "/app/build/virtual-node/setup.py", line 16, in node_install

           env_dir = os.environ['VIRTUAL_ENV']

         File "/app/.heroku/python/lib/python2.7/UserDict.py", line 23, in __getitem__

           raise KeyError(key)

       KeyError: 'VIRTUAL_ENV'

       ----------------------------------------
       Command python setup.py egg_info failed with error code 1 in /app/build/virtual-node
```

Got  user-env-compile ON, so not sure what is the reason - either Heroku does not use virtualenv or there should be some other way to get path to install Node to

**Comment by roadsideseb** [comment]
I haven't tried installing it on heroku until just now. From a bit of research it seems that heroku isn't using the usual virtualenv setup. Installing flask put it into `/app/.heroku/python/lib/python2.7/site-packages` instead of a virtualenv package. Hence, there is no `VIRTUAL_ENV`. Making this work properly in a non-virtualenv environment could get a bit tricky. I'd have to look into this a bit more as I am not sure how easy/difficult this would be.

The partly good news is, you could try a workaround to install `virtual-node` in heroku. Add a config variable to your heroku environment with a command similar to this:

```
heroku config:add VIRTUAL_ENV=/app/.heroku/venv
```

This will install it just fine but with a few drawbacks:
1. The compilation will run every time you deploy to heroku
2. You can only access the node executable `node` by using its full path or adding it manually to your `PATH`.

I hope this helps.

**Comment by keiw** [comment]
Thanks for quick response,

in my use-case Node.js on Heroku is needed juts for LESS compilation and  i would think about using both virtula-(node| | less) together.

Right now i fall back to using this [post-compile script](https://github.com/nigma/heroku-django-cookbook/blob/master/bin/install_nodejs) which should have the same 1. drawback you'v mentioned but from my experience Heroku caches results so i do not see node distribution been downloaded every time on deployment.

Regarding 2. - that script just symlinks node executable to /app/.heroku/python/bin/node which looks to be already in the PATH, where /app/.heroku/python/ looks like virtual environment itself.

Does that make any sense?

**Comment by dmpayton** [comment]
I also need to compile LESS on Heroku, and I've implemented a fix that skips the install process if it detects that the specified version of Node is already installed to the virtualenv. This has brought my Heroku deployment times from ~13 minutes down to ~7 minutes.

https://github.com/dmpayton/virtual-node/commit/1f749b5bb8c19bb2b8dbbf76884884acce6593ed

There may be a better way to do this, and I'm mainly looking for feedback before creating a pull request.

Edit: My patch still requires settings VIRTUAL_ENV (in my case, to `/app/.heroku/python`)

**Comment by roadsideseb** [comment]
Thanks @dmpayton. That's a pretty good addition and I cherry-picked it into the master branch. It's part of the latest release 0.0.2 that I just pushed to PyPI with some additional fixes.

I am closing this issue as I don't think there is a better solution for this than the above workaround. Feel free to open up a new issue if you have suggestions for a different solution.
